name: fundoc
# https://github.com/CSSSR/fundoc-action

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  fundoc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Fundoc Action
        uses: daynin/fundoc-action@v0.2.1

      - name: update highlight.js
        run: |
          cp docs/highlight.js docs/fundoc

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'docs: generate documentation'
